feat: add hex_format param to chain related rpc
nervosnetwork/ckb pull request #2248
Opened 2020-08-26 09:24 UTC by quake

This PR adds an optional `hex_format` param to chain related rpc, returns data in hex format without calculated hash values, it will improve performance in some scenarios, for example, ckb-indexer can scan 2,000,000 blocks in 13 minutes with this change (before: 20 minutes)

2020-08-26 09:52 UTC, zhangsoledad commented
I suggest using `verbosity`, this has been widely accepted. description comes easier.
https://bitcoin-rpc.github.io/en/doc/0.17.99/rpc/blockchain/getblock/
we may consider return information block only contains tx_hash later.

2020-08-27 06:55 UTC, doitian commented
Does it return hex data without decoding? The doc “without calculated hash values” is misleading.

2020-08-27 06:57 UTC, doitian commented
It’s better to give example responses when hex format is choosed

2020-08-27 07:41 UTC, quake commented
> I suggest using `verbosity` and `verbose`, this has been widely accepted. description comes easier.
> https://bitcoin-rpc.github.io/en/doc/0.17.99/rpc/blockchain/getblock/
> https://bitcoin-rpc.github.io/en/doc/0.17.99/rpc/rawtransactions/getrawtransaction/
> we may consider return information block only contains tx_hash later.

I decided to use an unified numeric type `verbosity` params for all hex encoding rpc, please review again, thanks.

2020-08-27 07:48 UTC, quake commented
> It’s better to give example responses when hex format is choosed

I've updated the rpc document format, added markdown link in the params description, it will help user to understand the hex encoding format better, however, still cannot write the example hex response in doc because of the format limitation.

2020-08-31 08:20 UTC, doitian requested changes

2020-08-31 08:20 UTC, doitian commented on rpc/json/rpc.json
> +                "verbosity": "0 for a json object, 1 for hex encoded [Header](../util/types/schemas/blockchain.mol#L84) data, an optional parameter, default is 0"
Isn't json more verbose than hex? 🤣 

From bitcoin

```
0 for hex encoded data, 1 for a json object, and 2 for json object with transaction data
```

2020-08-31 08:20 UTC, doitian commented on rpc/README.md
> +* with_data - Boolean
A candidate to be replaced by `verbosity` later.

2020-09-02 02:09 UTC, quake commented on rpc/json/rpc.json
> +                "verbosity": "0 for a json object, 1 for hex encoded [Header](../util/types/schemas/blockchain.mol#L84) data, an optional parameter, default is 0"
Updated, please review again, thanks.

2020-09-04 08:28 UTC, doitian approved these changes

2020-09-04 08:31 UTC, zhangsoledad approved these changes

2020-09-04 09:23 UTC, quake commented on rpc/json/rpc.json
> +                "verbosity": "2 for a json object, 0 for hex encoded [Block](../util/types/schemas/blockchain.mol#L94) data, an optional parameter, default is 2"
will create a PR later: return block only contains tx_hash in json format and use the verbosity=1

2020-09-04 09:24 UTC, quake commented
bors r+

2020-09-04 09:24 UTC, quake commented
bors r=doitian,zhangsoledad

2020-09-04 10:14 UTC, merged