feat: allows deprecated rpc method by adding `deprecated.` prefix to the rpc name
nervosnetwork/ckb pull request #2251
Opened 2020-08-27 10:29 UTC by quake

resolve https://github.com/nervosnetwork/ckb/issues/2247

2020-08-31 07:58 UTC, doitian commented
According to #2247, we need a window to notify that an RPC has been deprecated. During the window, users must be able to continue using the methods without any changes.

And I think renaming the RPC method name is not a friend deprecation mechanism, it requires updating client code. I prefer the solution used by bitcoin, in which user must listed the enabled deprecated methods in the command line arguments.

2020-08-31 07:59 UTC, doitian requested changes
We need a two stage deprecation mechanism, see https://github.com/nervosnetwork/ckb/issues/2247

2020-08-31 08:00 UTC, quake commented
> According to #2247, we need a window to notify that an RPC has been deprecated. During the window, users must be able to continue using the methods without any changes.
> 
> And I think renaming the RPC method name is not a friend deprecation mechanism, it requires updating client code. I prefer the solution used by bitcoin, in which user must listed the enabled deprecated methods in the command line arguments.

this PR doesn't rename rpc method, please review again, thanks.

2020-08-31 08:30 UTC, doitian submitted a review, later dismissed

2020-09-02 02:26 UTC, yangby-cryptape submitted a review, later dismissed

2020-09-03 09:14 UTC, quake commented
bors r=doitian,yangby-cryptape

2020-09-04 09:45 UTC, doitian approved these changes

2020-09-06 09:46 UTC, zhangsoledad approved these changes

2020-09-06 09:47 UTC, zhangsoledad commented
bors r=doitian,zhangsoledad,yangby-cryptape

2020-09-06 10:35 UTC, merged