feat: chain spec check
nervosnetwork/ckb pull request #2255
Opened 2020-09-01 12:44 UTC by zhangsoledad

2020-11-05 07:49 UTC, doitian commented on ckb-bin/src/subcommand/replay.rs
> +            sanity_check(shared, chain, args.full_verification);
🙄

2020-11-05 08:12 UTC, doitian commented on util/app-config/src/cli.rs
> +                .help("Enforce consistency check on chain-spec and storage"),
```suggestion
                .help("Skips checking the chain spec with the hash stored in the database"),
```

2020-11-05 08:51 UTC, doitian approved these changes

2020-11-05 08:51 UTC, doitian commented on ckb-bin/src/subcommand/run.rs
> +                "chain_spec_hash mismatch Config({}) storage({})",
```suggestion
                "chain_spec_hash mismatch Config({}) storage({}), pass command line argument --skip-spec-check if you are sure that the two different chains are compatible.",
```

The suggested change may require `cargo fmt`

2020-11-05 08:54 UTC, doitian requested changes
Request the error message change so user know how to skip the check.

2020-11-06 03:49 UTC, doitian submitted a review, later dismissed

2020-11-11 10:19 UTC, doitian commented
@zhangsoledad CI failed

2020-11-11 10:35 UTC, keroro520 submitted a review, later dismissed

2020-11-11 12:35 UTC, keroro520 approved these changes

2020-11-12 02:01 UTC, doitian approved these changes

2020-11-12 02:02 UTC, doitian commented
bors r=doitian,keroro520

2020-11-12 02:53 UTC, merged