chore: integration test - put case log together
nervosnetwork/ckb pull request #2278
Opened 2020-09-14 03:46 UTC by chuijiaolianying

When debug integration case in local, we may run a single case lots time, then there is a big problem how to find the logs under an execution.

Old log structure:
```
├── ckb-it-get_blocks_timeout-net-G65fZ4
├── ckb-it-get_blocks_timeout-node0-LZRUJE
├── ckb-it-get_blocks_timeout-node1-11uL3C
```
New log structure:
```
├── ckb-it-get_blocks_timeout-UccnLI
│   ├── net
│   ├── node0
│   └── node1
```

2020-09-17 07:43 UTC, doitian approved these changes

2020-09-18 07:40 UTC, quake requested changes

2020-09-18 07:40 UTC, quake commented on test/src/node.rs
> +            .to_string();
unnecessary `as_path`

```suggestion
        let working_dir = case_working_dir
            .join(node_index)
            .display()
            .to_string();
```

2020-09-18 07:40 UTC, quake commented on test/src/net.rs
> +            working_dir: case_working_dir.join("net").as_path().display().to_string(),
unnecessary as_path

```
working_dir: case_working_dir.join("net").display().to_string(),
```

2020-09-18 07:40 UTC, quake commented on test/src/net.rs
> +            working_dir: case_working_dir.join("net").as_path().display().to_string(),
It would be a good chance for us to refactor working_dir field to `PathBuf` in this PR.

2020-09-19 00:04 UTC, chuijiaolianying commented
@quake @doitian  please take another look, thx

2020-09-21 03:18 UTC, quake approved these changes

2020-09-21 06:08 UTC, yangby-cryptape approved these changes

2020-09-21 06:20 UTC, chuijiaolianying commented
bors r=quake,yangby-cryptape

2020-09-21 07:08 UTC, merged