chore: upgrade tentacle, enable reuse port
nervosnetwork/ckb pull request #2333
Opened 2020-10-23 05:26 UTC by driftluo

2020-11-04 06:07 UTC, doitian submitted a review, later dismissed

2020-11-04 06:13 UTC, yangby-cryptape approved these changes

2020-11-04 06:33 UTC, quake requested changes

2020-11-04 06:33 UTC, quake commented on network/src/protocols/discovery/mod.rs
> +                            } else if version == state::REUSE_PORT_VERSION {
we should consider future version upgrade
```suggestion
                            } else if version >= state::REUSE_PORT_VERSION {
```

2020-11-04 07:59 UTC, quake submitted a review, later dismissed

2020-11-05 01:40 UTC, doitian submitted a review, later dismissed

2020-11-05 02:28 UTC, driftluo commented
bors r=quake,doitian

2020-11-05 03:18 UTC, driftluo commented
bors retry

2020-11-05 04:33 UTC, driftluo commented
bors retry

2020-11-05 07:14 UTC, doitian approved these changes

2020-11-06 06:37 UTC, quake approved these changes

2020-11-06 06:38 UTC, doitian commented
bors r=quake,doitian

2020-11-06 07:28 UTC, merged