feat: add with_sentry feature
nervosnetwork/ckb pull request #2351
Opened 2020-11-09 06:19 UTC by quake

move sentry to optional dependency, reduce dependency libs on other target (wasm32, etc)

2020-11-11 05:22 UTC, driftluo approved these changes

2020-11-11 07:46 UTC, keroro520 requested changes

2020-11-11 07:46 UTC, keroro520 commented on ckb-bin/Cargo.toml
> +with_sentry = ["ckb-network/with_sentry", "ckb-sync/with_sentry", "ckb-app-config/with_sentry", "ckb-logger-service/with_sentry"]
Should "sentry" be optional here?

2020-11-12 05:48 UTC, quake commented on ckb-bin/Cargo.toml
> +with_sentry = ["ckb-network/with_sentry", "ckb-sync/with_sentry", "ckb-app-config/with_sentry", "ckb-logger-service/with_sentry"]
updated, please review again.

2020-11-12 05:51 UTC, keroro520 approved these changes

2020-11-18 02:19 UTC, doitian approved these changes

2020-11-18 02:19 UTC, doitian commented
bors r=doitian,keroro520

2020-11-18 11:48 UTC, merged