chore: expose jsonrpc types for subscription
nervosnetwork/ckb pull request #2353
Opened 2020-11-09 06:44 UTC by yangby-cryptape

At present, write a subscription client have to copy those codes or depend on the server crate.
It doesn't make sense.

2020-11-09 06:54 UTC, zhangsoledad approved these changes

2020-11-09 06:54 UTC, quake approved these changes

2020-11-11 08:41 UTC, keroro520 requested changes

2020-11-11 08:41 UTC, keroro520 commented on util/jsonrpc-types/src/subscription.rs
> +#[derive(Serialize, Deserialize, PartialEq, Eq, Hash)]
```suggestion
#[derive(Serialize, Deserialize, PartialEq, Eq, Hash, Debug)]
```

2020-11-11 09:06 UTC, yangby-cryptape commented on util/jsonrpc-types/src/subscription.rs
> +#[derive(Serialize, Deserialize, PartialEq, Eq, Hash)]
DONE!

2020-11-11 09:29 UTC, keroro520 approved these changes

2020-11-11 09:43 UTC, zhangsoledad submitted a review, later dismissed

2020-11-12 02:03 UTC, doitian approved these changes

2020-11-12 02:18 UTC, doitian commented
0001-docs-rpc-fix-rpc-doc-for-Topic.patch

```diff
From e53a919638cc987037f750768564c4e59d522d62 Mon Sep 17 00:00:00 2001
From: ian <ian@nervos.org>
Date: Thu, 12 Nov 2020 10:16:18 +0800
Subject: [PATCH] docs(rpc): fix rpc doc for Topic

---
 devtools/doc/rpc.py | 7 +++++--
 1 file changed, 5 insertions(+), 2 deletions(-)

diff --git a/devtools/doc/rpc.py b/devtools/doc/rpc.py
index 06613bd1f..4578cce11 100755
--- a/devtools/doc/rpc.py
+++ b/devtools/doc/rpc.py
@@ -84,7 +84,10 @@ def write_method_signature(file, method_name, vars):
             file.write('    * `{}`: {}\n'.format(var.name, var.ty))
     else:
         file.write('* `{}()`\n'.format(method_name))
-    file.write('* result: {}\n'.format(vars[-1].ty))
+    if method_name == 'subscribe':
+        file.write('* result: `string`\n')
+    else:
+        file.write('* result: {}\n'.format(vars[-1].ty))
 
 
 class MarkdownParser():
@@ -674,7 +677,7 @@ class RPCDoc(object):
 
         if 'ckb_types/packed' in path:
             return
-        if path.split('/')[-1] in ['type.Result.html', 'struct.Subscriber.html', 'enum.SubscriptionId.html']:
+        if path.split('/')[-1] in ['type.Result.html', 'struct.Subscriber.html', 'enum.SubscriptionId.html', 'enum.Topic.html']:
             return
 
         with open(path) as file:
-- 
2.29.2
```

2020-11-12 06:37 UTC, keroro520 approved these changes

2020-11-13 00:47 UTC, quake approved these changes

2020-11-17 16:18 UTC, zhangsoledad approved these changes

2020-11-17 16:19 UTC, zhangsoledad commented
bors r=quake,zhangsoledad

2020-11-18 02:20 UTC, doitian commented
bors retry

2020-11-18 04:35 UTC, doitian approved these changes

2020-11-18 04:57 UTC, zhangsoledad commented
bors retry

2020-11-18 05:45 UTC, merged