tx pool callback
nervosnetwork/ckb pull request #2365
Opened 2020-11-18 08:30 UTC by zhangsoledad

2020-11-27 06:19 UTC, yangby-cryptape commented on util/types/src/core/service.rs
> +pub enum PoolTransactionReject {
```suggestion
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(tag = "type", content = "description")]
pub enum PoolTransactionReject {
```

So, the return looks like the follow structure:
```javascript
[
    // first item is the `PoolTransactionEntry`
    {
        "transaction": { ... /* omit */ ... }
    },
    // second item is the `PoolTransactionReject`
    {
        "type": "Resolve",
        "description": "Resolve failed Dead(OutPoint(...))"
    }
]  
```

2020-11-27 06:42 UTC, yangby-cryptape commented
If a proposed transaction doesn't be committed during the proposed window, subscribers couldn't know that.

2020-11-27 08:46 UTC, yangby-cryptape commented
I have tested, both methods work well.

2020-11-29 21:34 UTC, zhangsoledad commented
benchmark

2020-12-14 00:44 UTC, quake approved these changes

2020-12-22 01:10 UTC, doitian requested changes

2020-12-22 01:10 UTC, doitian commented on rpc/src/module/subscription.rs
> +                    recv(proposed_transaction_receiver) -> msg => match msg {
Please document new subscription topics in `SubscriptionRpc::subscribe`.

2020-12-23 03:10 UTC, doitian submitted a review, later dismissed
I'll fix the RPC doc link later

2020-12-23 03:22 UTC, doitian commented
Test failed:

```
thread 'tests::block_assembler::test_block_template_timestamp' panicked at 'assertion failed: `(left == right)`
  left: `1608657504170`,
 right: `11`', chain/src/tests/block_assembler.rs:157:5
```

2020-12-23 09:51 UTC, keroro520 requested changes

2020-12-23 09:51 UTC, keroro520 commented on notify/src/lib.rs
> +            .expect("Subscribe new transaction should be OK")
panic messages should be "Subscribe proposed transaction ...".
And also `subscribe_reject_transaction`

2020-12-23 11:39 UTC, keroro520 commented
LGTM
I have reviewed and tested this PR

2020-12-23 11:59 UTC, keroro520 approved these changes

2020-12-23 14:58 UTC, keroro520 approved these changes

2020-12-24 01:49 UTC, doitian approved these changes

2020-12-24 01:49 UTC, doitian commented
bors r=doitian,keroro520

2020-12-24 02:37 UTC, merged