refactor: single instance async runtime
nervosnetwork/ckb pull request #2373
Opened 2020-11-23 09:36 UTC by zhangsoledad

2020-11-23 09:36 UTC, zhangsoledad commented
benchmark

2020-11-26 06:15 UTC, driftluo submitted a review, later dismissed

2020-11-26 06:55 UTC, yangby-cryptape approved these changes

2020-11-27 01:45 UTC, doitian commented on shared/src/shared.rs
> +    /// TODO(doc): @quake
Please document the new functions.

2020-11-27 01:46 UTC, doitian requested changes
Please document the new functions instead of adding TODOs.

2020-11-27 07:20 UTC, zhangsoledad commented on shared/src/shared.rs
> +    /// TODO(doc): @quake
Ouch 🦀

2020-11-27 07:25 UTC, zhangsoledad commented on ckb-bin/Cargo.toml
> +with_sentry = ["sentry", "ckb-network/with_sentry", "ckb-sync/with_sentry", "ckb-app-config/with_sentry", "ckb-logger-service/with_sentry"]
feed newline ☕

2020-11-27 07:34 UTC, zhangsoledad commented on ckb-bin/Cargo.toml
> +with_sentry = ["sentry", "ckb-network/with_sentry", "ckb-sync/with_sentry", "ckb-app-config/with_sentry", "ckb-logger-service/with_sentry"]
just feed newline ☕

2020-11-28 07:09 UTC, doitian approved these changes

2020-11-30 01:38 UTC, yangby-cryptape approved these changes

2020-11-30 07:03 UTC, driftluo approved these changes

2020-11-30 17:00 UTC, zhangsoledad commented
bors r=doitian, yangby-cryptape, driftluo

2020-11-30 17:49 UTC, merged