chore(integration): add sentry section into ckb.toml
nervosnetwork/ckb pull request #2381
Opened 2020-12-01 09:34 UTC by chuijiaolianying

After https://github.com/nervosnetwork/ckb/pull/2351, integration test cannot run for ckb which builds with `--features with_sentry`.

2020-12-01 10:01 UTC, quake commented
I'm confused because we don't use sentry in the integration test, why sentry configuration is required here?

2020-12-01 10:25 UTC, chuijiaolianying commented
> I'm confused because we don't use sentry in the integration test, why sentry configuration is required here?

If ckb builds without `--features with_sentry`, sentry configuration is not required and everything works well. 

But if ckb builds with `--features with_sentry` (such as release version), sentry configuration is required, or we will meet a config error: `Config Error: Error { inner: ErrorInner { kind: Custom, line: Some(88), col: 0, at: Some(1738), message: "missing field `sentry`", key: [] } }`

Besides, I think in CI we should use the same command when build ckb like build release version as far as possible.

2020-12-02 02:19 UTC, keroro520 requested changes

2020-12-02 02:19 UTC, keroro520 commented on test/src/node.rs
> +
https://github.com/nervosnetwork/ckb/blob/develop/test/template/ckb.toml#L18-L23 the test-used `ckb.toml` has configured `[sentry]`, why attach a new one here?

2020-12-02 02:19 UTC, keroro520 commented on test/src/node.rs
> +use std::io::prelude::*;
Why we need the import of `std::io::preclude::*`? Try to remove it or import what we require only.

2020-12-02 03:54 UTC, chuijiaolianying commented
@quake  @keroro520  please take another look, thx

2020-12-02 03:57 UTC, quake approved these changes

2020-12-02 03:59 UTC, keroro520 approved these changes

2020-12-02 07:30 UTC, quake commented
bors r=quake,keroro520

2020-12-04 07:59 UTC, doitian commented
bors retry

2020-12-07 01:39 UTC, doitian commented
bors retry

2020-12-14 05:48 UTC, doitian approved these changes

2020-12-14 05:51 UTC, doitian commented
bors retry

2020-12-15 00:50 UTC, chuijiaolianying commented
bors retry

2020-12-15 01:38 UTC, merged