docs: document ckb-app-config
nervosnetwork/ckb pull request #2436
Opened 2020-12-15 11:00 UTC by doitian

2020-12-15 12:00 UTC, yangby-cryptape requested changes

2020-12-15 12:00 UTC, yangby-cryptape commented on util/app-config/src/configs/db.rs
> +    /// Canonicalizes pathes in the config options.
```suggestion
    /// Canonicalizes paths in the config options.
```

2020-12-15 12:00 UTC, yangby-cryptape commented on util/app-config/src/cli.rs
> +/// Parse the command line argumets by supplying the version information.
```suggestion
/// Parse the command line arguments by supplying the version information.
```

2020-12-15 12:00 UTC, yangby-cryptape commented on util/app-config/src/args.rs
> +    /// Whether to promopt user inputs interactively.
```suggestion
    /// Whether to prompt user inputs interactively.
```

2020-12-16 09:20 UTC, yangby-cryptape submitted a review, later dismissed

2021-01-07 10:04 UTC, zhangsoledad approved these changes

2021-01-13 08:37 UTC, doitian commented
Resolved conflicts with #2501

2021-01-14 03:25 UTC, quake approved these changes

2021-02-09 04:20 UTC, doitian commented
Resolved conflicts

2021-02-09 04:23 UTC, quake approved these changes

2021-02-09 06:42 UTC, yangby-cryptape approved these changes

2021-02-09 10:23 UTC, doitian commented
bors r=quake,yangby-cryptape

2021-02-09 11:18 UTC, merged