docs: document errors
nervosnetwork/ckb pull request #2456
Opened 2020-12-22 08:12 UTC by keroro520

2020-12-22 08:26 UTC, yangby-cryptape requested changes

2020-12-22 08:26 UTC, yangby-cryptape commented on error/src/util.rs
> +/// impl_error_conversion_with_kind!(SourceType, error_kind, TargetType)
```suggestion
/// ```ignore
/// impl_error_conversion_with_kind!(SourceType, error_kind, TargetType);
```

I didn't run the tests, but I guess this code couldn't pass `cargo run`.

2020-12-22 08:26 UTC, yangby-cryptape commented on error/src/util.rs
> +/// ```rust
```suggestion
/// ```ignore
```

2020-12-22 08:26 UTC, yangby-cryptape commented on error/src/util.rs
> +/// ```rust
```suggestion
/// ```ignore
```

2020-12-22 08:26 UTC, yangby-cryptape commented on error/src/util.rs
> +/// impl_error_conversion_with_adaptor!(SourceType, AdaptorType, TargetType)
```suggestion
/// ```ignore
/// impl_error_conversion_with_adaptor!(SourceType, AdaptorType, TargetType);
```

2020-12-22 08:26 UTC, yangby-cryptape commented on error/Cargo.toml
> +description = "underlying error types used over ckb crates"
```suggestion
description = "Underlying error types used over ckb crates"
```

2020-12-22 08:26 UTC, yangby-cryptape commented on util/types/src/core/error.rs
> +    /// There is a dependancy header that is immature yet.
```suggestion
    /// There is a dependency header that is immature yet.
```

2020-12-22 08:26 UTC, yangby-cryptape commented on util/dao/src/lib.rs
> +    /// Calculates the new dao field after packaging these transactions. It returns the dao field in [`Byte32`] format. Please see [`extract_dao_data`] if you intend to see the detailed content.
```suggestion
    /// Calculates the new dao field after packaging these transactions. It returns the dao field in [`Byte32`] format.
    /// Please see [`extract_dao_data`] if you intend to see the detailed content.
```

Too long.

2020-12-24 02:13 UTC, keroro520 commented
@yangby-cryptape Thanks for your comments. Most of the suggestions applied, except for the long line.

There are so many long comments in this PR and original code; I would like to ignore this issue for the moment and unify them via [rustfmt comment_width](https://rust-lang.github.io/rustfmt/?version=master&search=#comment_width) later.

2020-12-25 05:44 UTC, yangby-cryptape approved these changes

2020-12-30 02:29 UTC, doitian approved these changes

2020-12-30 02:29 UTC, doitian commented
bors r=doitian,yangby-cryptape

2020-12-30 03:56 UTC, merged