docs: add missing documents for test-chain-utils
nervosnetwork/ckb pull request #2469
Opened 2020-12-23 11:22 UTC by chuijiaolianying

2020-12-24 02:25 UTC, keroro520 commented on util/test-chain-utils/src/chain.rs
> +/// Script for load input data hash from input data.
Suggest adding `#[doc(hidden)]` for test-used interfaces.

2020-12-24 02:38 UTC, keroro520 requested changes

2020-12-24 02:38 UTC, keroro520 commented on util/test-chain-utils/src/median_time.rs
> +/// the median timestamp of the previous 37 blocks.
The number of latest blocks to calculate the "median time" is specified via `BlockMedianTimeContext::median_block_count()`. [MockMedianTime says `11`](https://github.com/nervosnetwork/ckb/pull/2469/files#diff-44a2f5373da905a8c7c3fa4ccfdbe233f2e8db21799c417f2889e2460dd7cc22R17-R19)

2020-12-24 06:13 UTC, chuijiaolianying commented
@keroro520  Thanks for your suggestions, please take another look

2020-12-25 05:46 UTC, yangby-cryptape commented on util/test-chain-utils/src/chain.rs
> +/// Script for load input data hash from input data.
`to do` or `for doing`?

2020-12-25 06:51 UTC, chuijiaolianying commented on util/test-chain-utils/src/chain.rs
> +/// Script for load input data hash from input data.
Updated, please take another look, thx

2020-12-25 06:52 UTC, yangby-cryptape approved these changes

2020-12-30 02:23 UTC, doitian approved these changes

2020-12-30 02:23 UTC, doitian commented
ping @keroro520

2020-12-30 02:44 UTC, keroro520 approved these changes

2020-12-30 02:45 UTC, keroro520 commented
bors r=doitian,yangby-cryptape,keroro520

2020-12-30 03:56 UTC, merged