chore(integration): add cases RPC - Module stats
nervosnetwork/ckb pull request #2491
Opened 2021-01-04 08:30 UTC by chuijiaolianying

Add integration cases for RPC of module stats:
  - get_blockchain_info
  - get_peers_state

BTW, `get_peers_state` already deprecated since 0.12.0, why not delete it?

2021-01-11 03:19 UTC, keroro520 requested changes

2021-01-11 03:19 UTC, keroro520 commented on test/src/specs/rpc/get_peers_state.rs
> +            node1.rpc_client().get_peers_state().len(),
This RPC is deprecated.

2021-01-11 03:19 UTC, keroro520 commented on test/src/util/cell.rs
> +    );
This log is wrong when the current tip is not `0`.

maybe you can change to:

```
let to_mine = (out_bootstrap_period + count as u64 - 1).sub_saturate( node.get_tip_block_number() );
if to_mine > 0 {
  debug!(
    "... mine {} blocks ...", to_mine
  )
}
```

2021-01-11 03:19 UTC, keroro520 commented on test/src/util/mining.rs
> +    debug!("Mine block until all nodes out IBD mode.");
Not "all nodes", but just nodes in `nodes`.

2021-02-07 07:48 UTC, doitian commented
`get_peers_state` will be deleted soon, no need to add integration test for it.

2021-02-07 07:52 UTC, doitian commented
I'm OK with the changes. Just remove the test case on `get_peers_state`.

2021-02-08 09:35 UTC, doitian approved these changes

2021-02-25 06:25 UTC, keroro520 approved these changes

2021-02-25 06:25 UTC, keroro520 commented
@chuijiaolianying please resolve conflict

2021-02-25 06:41 UTC, doitian commented
@chuijiaolianying Please rebase and re-request the review.

2021-04-30 08:12 UTC, keroro520 commented
just a test: benchmark

2021-05-20 22:20 UTC, doitian commented
@keroro520 could you help to rebase this PR and re-submit it?

2021-05-22 05:22 UTC, keroro520 commented
> @keroro520 could you help to rebase this PR and re-submit it?

I have rebased and re-submitted as https://github.com/nervosnetwork/ckb/pull/2711

2021-05-22 05:22 UTC, closed without merging