chore: add impl for EpochNumberWithFraction which used for getting details of epoch
nervosnetwork/ckb pull request #2495
Opened 2021-01-05 08:27 UTC by chuijiaolianying

According to the suggestion of https://github.com/nervosnetwork/ckb/pull/2494#discussion_r551694750, add impl for `EpochNumberWithFraction`, this would be useful for get `epoch_number`, `epoch_index` and `epoch_length` from `EpochNumberWithFraction`

2021-01-06 01:18 UTC, yangby-cryptape requested changes
I

2021-01-06 01:18 UTC, yangby-cryptape commented on util/jsonrpc-types/src/primitive.rs
> +impl EpochNumberWithFraction {
#### Why I disagree with this PR?

- `EpochNumberWithFraction` is an `alias` not a `new-type`.

  https://github.com/nervosnetwork/ckb/blob/e171a8a0ea7c1506547cb563fd8d8f3d267013b2/util/jsonrpc-types/src/primitive.rs#L28

  So `impl EpochNumberWithFraction` is equal to `impl Uint64`.

  Why `epoch_number`, `epoch_index` and `epoch_length` can be get from all `Uint64`?
  For example, developers will found `Capacity` has getters `epoch_number`, `epoch_index` and `epoch_length`, they will be confused.

- Bad smells: Duplicated Code and Magic Numbers 

  A better example:
  https://github.com/nervosnetwork/ckb/blob/e171a8a0ea7c1506547cb563fd8d8f3d267013b2/util/types/src/core/extras.rs#L412-L414

#### Let's look at this in another way:

- You could `impl From<Uint64> for ckb_types::EpochNumberWithFraction;`.
- 
- (Reuse Code) Then, get `epoch_number`, `epoch_index` or `epoch_length` from `ckb_types::EpochNumberWithFraction`.

2021-01-07 08:06 UTC, yangby-cryptape approved these changes

2021-01-27 01:12 UTC, quake approved these changes

2021-01-27 01:14 UTC, quake commented
bors r=quake,yangby-cryptape

2021-01-27 02:02 UTC, merged