chore: add doc for db
nervosnetwork/ckb pull request #2498
Opened 2021-01-06 03:32 UTC by quake

2021-01-06 07:09 UTC, yangby-cryptape requested changes

2021-01-06 07:09 UTC, yangby-cryptape commented on db/src/write_batch.rs
> +/// Making an atomic commit of several writes.
```suggestion
/// Making an atomic commit of several write operations.
```

2021-01-06 07:09 UTC, yangby-cryptape commented on db/src/transaction.rs
> +/// A optimistic transaction database.
```suggestion
/// An optimistic transaction database.
```

2021-01-06 10:12 UTC, yangby-cryptape approved these changes

2021-01-07 10:04 UTC, zhangsoledad approved these changes

2021-01-08 07:32 UTC, yangby-cryptape commented
bors r=yangby-cryptape,zhangsoledad

2021-01-08 09:02 UTC, merged