manually trigger compaction after freeze
nervosnetwork/ckb pull request #2525
Opened 2021-01-17 10:34 UTC by zhangsoledad

2021-02-08 09:48 UTC, doitian requested changes

2021-02-08 09:48 UTC, doitian commented on freezer/src/freezer.rs
> +    ) -> Result<BTreeMap<packed::Byte32, (BlockNumber, u32)>, Error>
This is a public interface. Please add some document about the return type. What's returned in the map on success?

2021-02-08 09:48 UTC, doitian commented on util/snapshot/src/lib.rs
> +static IBD_FINISHED: AtomicBool = AtomicBool::new(false);
Global flag is not recommended. It makes test hard.

2021-02-25 05:46 UTC, doitian approved these changes

2021-02-25 06:53 UTC, doitian approved these changes

2021-02-25 10:41 UTC, yangby-cryptape approved these changes

2021-02-25 21:00 UTC, doitian approved these changes

2021-02-25 21:00 UTC, doitian commented
bors r=doitian,yangby-cryptape

2021-02-25 21:53 UTC, merged