feat: request the approval for database migrations
nervosnetwork/ckb pull request #2571
Opened 2021-02-19 01:18 UTC by yangby-cryptape

- docs: fix a typo
- chore: no migration version means the database is uninitialized
  At present, `migration_check` will return `true` if the database is uninitialized.
  But an uninitialized database doesn't have data required to migrate.
  This is important when do `migration_check` in `ckb run`.
- feat: request the approval for database migrations

2021-02-19 02:42 UTC, doitian requested changes

2021-02-19 02:42 UTC, doitian commented on ckb-bin/src/subcommand/migrate.rs
> +        if atty::is(atty::Stream::Stdin) && atty::is(atty::Stream::Stdout) {
No need to prompt if `builder.migration_check()` returns true.

2021-02-19 02:45 UTC, doitian commented
Some migrations may be very fast to execute, such as adding a single key into the database. We can let the migration tell whether it is time consuming, and only ask for confirmations in `ckb migration` and disable `ckb run` automatic migration when there’s at least a time consuming migration. However, it could be another PR.

2021-02-25 06:45 UTC, doitian approved these changes

2021-02-28 00:34 UTC, quake approved these changes

2021-02-28 01:01 UTC, yangby-cryptape commented
bors merge=doitian,quake

2021-02-28 01:52 UTC, yangby-cryptape commented
bors retry

2021-02-28 02:45 UTC, merged