perf: skip molecule checking in release build
nervosnetwork/ckb pull request #2579
Opened 2021-02-21 02:12 UTC by quake

we should view the the slice as infallible, trusted entity in release build, skip length and bounds check.

2021-02-21 02:14 UTC, quake commented
benchmark, sync-test

2021-02-21 23:58 UTC, quake commented
benchmark, sync-test

2021-02-22 01:12 UTC, chuijiaolianying commented
sync-test

2021-02-23 05:00 UTC, doitian requested changes
I'm against this PR. The function name suggests that it will panic on invalid data, it is surprising that it does not. It is very easy to be abused.

If we really want to skip the verification only in release mode, we should add a new function to do that.

2021-02-23 05:22 UTC, quake commented
> I'm against this PR. The function name suggests that it will panic on invalid data, it is surprising that it does not. It is very easy to be abused.
> 
> If we really want to skip the verification only in release mode, we should add a new function to do that.

how about change the name to `from_verified_slice_should_be_ok` and move it to store crate as a private trait?

2021-02-26 07:12 UTC, quake commented
sync-test

2021-03-03 04:22 UTC, doitian commented
> how about change the name to `from_verified_slice_should_be_ok` and move it to store crate as a private trait?

What's the reason that we cannot use `new_unchecked` in the places that we are sure the slice is valid but need to change the behavior of this function?

2021-03-03 05:04 UTC, yangby-cryptape commented
First, just an additional explanation:
Before the mainnet launched and the first month after mainnet launched, there are several panics in our sentry were caused because the format of data from storage were malformed, some of those panics were sent by this function `from_slice_should_be_ok(..)`.

Do no checks means we can make sure that:
- We would never make mistakes **again** when update data structures.
- The RocksDB will be always work well.

The worst situation I imagined is: no panics caused at beginning, but only malformed data, then we found the bug several days later.

Speaking of this, I remembered that in Matt Damon's film "The Martian", their rocket exploded because the NASA skip few checks which only have very very very small probability to find bugs.

Second, there no **strong** evidences could approve that those checks cost too many resource, so that we have to remove them.

2021-06-16 03:53 UTC, doitian commented
Close since it does not gains enough approvals.

2021-06-16 03:53 UTC, closed without merging