refactory tx-pool
nervosnetwork/ckb pull request #2634
Opened 2021-03-29 00:58 UTC by zhangsoledad

2021-03-29 01:26 UTC, zhangsoledad commented
benchmark

2021-03-30 06:40 UTC, yangby-cryptape approved these changes
It looks good to me.

Only a few issues about coding style in my opinion, and I think we can do optimization later, so that we can merge this big PR asap.

2021-03-30 07:33 UTC, quake requested changes

2021-03-30 07:33 UTC, quake commented on tx-pool/src/component/entry.rs
> +    // /// related out points (cell deps includes cell group itself)
Please remove commented out code

2021-03-30 07:33 UTC, quake commented on tx-pool/src/component/orphan.rs
> +            evicted += 1;
```suggestion
        let mut evicted = expires.len();
        for id in expires {
```

2021-03-30 07:33 UTC, quake commented on tx-pool/src/component/orphan.rs
> +            let id = self.entries.keys().cloned().next().expect("bound checked");
```suggestion
            let id = self.entries.keys().next().cloned().expect("bound checked");
```

2021-03-30 07:33 UTC, quake commented on tx-pool/src/component/orphan.rs
> +    pub fn limit_size(&mut self) -> u64 {
```suggestion
    pub fn limit_size(&mut self) -> usize {
```

2021-03-30 07:33 UTC, quake commented on tx-pool/src/pool.rs
> +    ) -> Option<(&TransactionView, Option<Cycle>)> {
I think the `Cycle` cannot be `None` after refactoring, we can change the return type to:

```suggestion
    ) -> Option<(&TransactionView, Cycle)> {
```

2021-03-30 07:33 UTC, quake commented on tx-pool/src/process.rs
> +    #[allow(unused_variables)]
unnecessary clippy hint?

2021-03-30 07:36 UTC, yangby-cryptape commented on benches/benches/benchmarks/overall.rs
> +    };
```suggestion
    let config = NetworkConfig {
        max_peers: 19,
        max_outbound_peers: 5,
        path: tmp_dir.path().to_path_buf(),
        ping_interval_secs: 15,
        ping_timeout_secs: 20,
        connect_outbound_interval_secs: 1,
        discovery_local_address: true,
        bootnode_mode: true,
        reuse: true,
        ..Default::default() 
    };
```

2021-04-05 11:43 UTC, zhangsoledad commented
benchmark

2021-04-05 13:36 UTC, quake approved these changes

2021-04-05 21:17 UTC, yangby-cryptape approved these changes

2021-04-05 21:18 UTC, yangby-cryptape commented
bors r=quake,yangby-cryptape

2021-04-05 22:13 UTC, merged