feat: better tips for "migrate" subcomamnd
nervosnetwork/ckb pull request #2854
Opened 2021-07-21 05:07 UTC by yangby-cryptape

#### Features
- Add a "silent" status for sub-commands to disable misleading log outputs.
- The command in help messages can be executed directly, without any modifies.

2021-07-21 12:15 UTC, doitian approved these changes

2021-07-21 12:17 UTC, doitian requested changes

2021-07-21 12:17 UTC, doitian commented on util/launcher/src/shared_builder.rs
> +                    Run `\"{}\" migrate -C \"{}\"` to migrate the data.\n\
```suggestion
                    Run `\"{}\" migrate -C \"{}\"` and confirm by typing \"YES\" to migrate the data.\n\
```

2021-07-21 13:23 UTC, zhangsoledad commented on util/launcher/src/shared_builder.rs
> +                    Run `\"{}\" migrate -C \"{}\"` to migrate the data.\n\
😢

2021-07-23 03:00 UTC, driftluo approved these changes

2021-07-23 09:27 UTC, doitian approved these changes

2021-07-23 09:45 UTC, yangby-cryptape commented
bors merge=driftluo,doitian

2021-07-23 11:56 UTC, merged