chore: panic if the database is corrupted
nervosnetwork/ckb pull request #2859
Opened 2021-07-22 10:25 UTC by yangby-cryptape

_Fix the issue posted by @doitian in https://github.com/nervosnetwork/ckb/issues/2855#issuecomment-884140994._

2021-07-22 10:26 UTC, keroro520 approved these changes

2021-07-22 22:09 UTC, doitian approved these changes

2021-07-22 22:48 UTC, doitian requested changes
Hold. I'll merge it later.

2021-07-23 07:07 UTC, quake approved these changes

2021-07-29 06:18 UTC, yangby-cryptape commented
Hold.

2021-07-30 10:12 UTC, doitian commented
Merged

2021-07-30 10:12 UTC, closed without merging