Workflow for Smoking test suite
nervosnetwork/ckb pull request #2861
Opened 2021-07-23 01:52 UTC by liya2017

2021-07-23 01:59 UTC, yangby-cryptape commented on devtools/somking_test/tip_block_growth_check.sh
> +echo "Fsirt tip block number is "$FIRST_TIP_BLOCK_NUMBER
```suggestion
echo "First tip block number is "$FIRST_TIP_BLOCK_NUMBER
```

2021-07-28 09:21 UTC, doitian requested changes

2021-07-28 09:21 UTC, doitian commented on .github/workflows/smoking_test.yaml
> +    steps:
I think we can use `workflow_dispatch` and `repository_dispatch` to trigger this workflow with the input to the CKB package URL. In `package.yml` we can trigger smoking test with the Linux package URL. So we can save the time to build CKB and just use the provided package to run the smoking test.

2021-08-02 04:14 UTC, keroro520 submitted a review, later dismissed
LGTM

2021-08-02 07:08 UTC, liya2017 commented
Add `repository_dispatch` based on Ian's comments

2021-08-03 01:28 UTC, keroro520 approved these changes

2021-08-04 03:19 UTC, doitian approved these changes

2021-08-04 03:19 UTC, doitian commented
Blocking by reviewers @keroro520 @yangby-cryptape

2021-08-04 04:48 UTC, keroro520 approved these changes

2021-08-04 04:49 UTC, keroro520 commented
bors r=doitian,keroro520

2021-08-04 05:55 UTC, merged