fix: metrics: there is no reactor running
nervosnetwork/ckb pull request #2897
Opened 2021-08-03 09:10 UTC by yangby-cryptape

Since CI scripts in old `rc/v*` branches couldn't work, I ran tests in my laptop:
- Rustfmt, clippy, hashes test, wasm test, bench test, unit tests and integration tests are passed.

2021-08-03 09:17 UTC, keroro520 approved these changes

2021-08-03 13:08 UTC, zhangsoledad commented on sync/src/synchronizer/mod.rs
> +        synchronizer.shared().state().tip_synced(state);
introduce by
https://github.com/nervosnetwork/ckb/commit/5a1f2b255c83fb56026493bff79b7f40adb1d861

2021-08-03 13:59 UTC, zhangsoledad submitted a review, later dismissed
Checks passed locally.

2021-08-03 20:15 UTC, doitian commented
Try to checkout ci.yaml from develop branch to see whether it works in rc/v0.43

2021-08-04 00:54 UTC, doitian requested changes
Let's make CI work for 0.43 in this PR. We'll maintain 0.43 for a long time.

2021-08-06 19:05 UTC, doitian approved these changes

2021-08-07 00:22 UTC, driftluo approved these changes

2021-08-07 21:23 UTC, doitian commented
bors r=doitian,driftluo

2021-08-08 21:37 UTC, merged