test: freeze block with extension
nervosnetwork/ckb pull request #2898
Opened 2021-08-03 12:42 UTC by zhangsoledad

2021-08-04 01:07 UTC, doitian requested changes

2021-08-04 01:07 UTC, doitian commented on store/src/db.rs
> +    fn freeze_with_extension() {
We must cover another scenario:

> The block is saved without extension using the old schema, and we must load it successfully from frozen files using the new version schema.

2021-08-04 01:49 UTC, yangby-cryptape submitted a review, later dismissed

2021-08-05 14:17 UTC, doitian approved these changes

2021-08-05 15:38 UTC, yangby-cryptape approved these changes

2021-08-05 17:09 UTC, zhangsoledad commented
bors r=doitian, yangby-cryptape

2021-08-05 18:21 UTC, merged