test: use grcov to generate coverage report
nervosnetwork/ckb pull request #2940
Opened 2021-08-11 08:24 UTC by quake

This PR changed the coverage report tool from tarpaulin to [grcov](https://github.com/mozilla/grcov), grcov is more simple to set up and it provides reporting for branches and calls count. Just run `make cov`, a `lcov-unit-test.info` file will be genearted in the root path. You can use some IDE [extension](https://github.com/ryanluker/vscode-coverage-gutters) to view the generated report, for example: 

![image](https://user-images.githubusercontent.com/8990/128995539-dbef3bc6-283f-40df-9781-46a225dfcbc5.png)

2021-08-11 08:26 UTC, quake commented
according to [grocv doc](https://github.com/mozilla/grcov#grcov-with-travis), `lcov.info` file can be uploaded to codecov.io by one-line:
```
bash <(curl -s https://codecov.io/bash) -f lcov.info
```

I will create a new PR to add this to CI.

2021-08-11 10:26 UTC, doitian requested changes

2021-08-11 10:26 UTC, doitian commented on Makefile
> +	grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov-unit-test.info
```suggestion
	grcov . --binary-path "${CARGO_TARGET_DIR}/debug/" -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov-unit-test.info
```

2021-08-11 10:26 UTC, doitian commented on Makefile
> +	grcov . --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov-integration-test.info
```suggestion
	grcov . --binary-path "${CARGO_TARGET_DIR}/debug/" -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov-integration-test.info
```

2021-08-11 10:31 UTC, doitian commented
> according to [grocv doc](https://github.com/mozilla/grcov#grcov-with-travis), `lcov-unit-test.info` file can be uploaded to codecov.io by one-line:
> 
> ```
> bash <(curl -s https://codecov.io/bash) -f lcov-unit-test.info
> ```
> 
> I will create a new PR to add this to CI.

I recommend adding a Makefile target to upload local report to codecov first.

2021-08-11 10:40 UTC, doitian commented
> > according to [grocv doc](https://github.com/mozilla/grcov#grcov-with-travis), `lcov-unit-test.info` file can be uploaded to codecov.io by one-line:
> > ```
> > bash <(curl -s https://codecov.io/bash) -f lcov-unit-test.info
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I will create a new PR to add this to CI.
> 
> I recommend adding a Makefile target to upload local report to codecov first.

```
curl -Os https://uploader.codecov.io/latest/linux/codecov

chmod +x codecov
./codecov -t ${CODECOV_TOKEN}
```

2021-08-11 10:42 UTC, quake commented
> > I will create a new PR to add this to CI.
> 
> It seems our CI is too poor so that it can't bear that. 😢

I plan to add a schedule action to upload develop branch coverage report only once per day.

2021-08-12 01:08 UTC, quake commented
> > > according to [grocv doc](https://github.com/mozilla/grcov#grcov-with-travis), `lcov-unit-test.info` file can be uploaded to codecov.io by one-line:
> > > ```
> > > bash <(curl -s https://codecov.io/bash) -f lcov-unit-test.info
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I will create a new PR to add this to CI.
> > 
> > 
> > I recommend adding a Makefile target to upload local report to codecov first.
> 
> ```
> curl -Os https://uploader.codecov.io/latest/linux/codecov
> 
> chmod +x codecov
> ./codecov -t ${CODECOV_TOKEN}
> ```

I have uploaded it via curl:

```
curl -X POST \
  --data-binary @lcov-unit-test.info \
"https://codecov.io/upload/v2?commit=xxx&token=xxx&flags=unit"

curl -X POST \
  --data-binary @lcov-integration-test.info \
"https://codecov.io/upload/v2?commit=xxx&token=xxx&flags=integration"
```

check out:
https://app.codecov.io/gh/nervosnetwork/ckb

2021-08-12 01:09 UTC, quake commented
> > > according to [grocv doc](https://github.com/mozilla/grcov#grcov-with-travis), `lcov-unit-test.info` file can be uploaded to codecov.io by one-line:
> > > ```
> > > bash <(curl -s https://codecov.io/bash) -f lcov-unit-test.info
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I will create a new PR to add this to CI.
> > 
> > 
> > I recommend adding a Makefile target to upload local report to codecov first.
> 
> ```
> curl -Os https://uploader.codecov.io/latest/linux/codecov
> 
> chmod +x codecov
> ./codecov -t ${CODECOV_TOKEN}
> ```

I have uploaded it via curl:

```
curl -X POST \
  --data-binary @lcov-unit-test.info \
"https://codecov.io/upload/v2?commit=xxx&token=xxx&flags=unit"

curl -X POST \
  --data-binary @lcov-integration-test.info \
"https://codecov.io/upload/v2?commit=xxx&token=xxx&flags=integration"
```

check out:
https://app.codecov.io/gh/nervosnetwork/ckb

2021-08-12 01:47 UTC, doitian approved these changes

2021-08-16 07:21 UTC, doitian commented
@keroro520 @driftluo please review

2021-08-16 12:25 UTC, keroro520 approved these changes

2021-08-16 12:26 UTC, keroro520 commented
bors r=doitian,keroro520

2021-08-16 12:57 UTC, merged