feat: upload coverage report artifact
nervosnetwork/ckb pull request #2981
Opened 2021-08-26 03:05 UTC by liya2017

### What problem does this PR solve?
Upload coverage report artifact

### Check List 

Tests

- Unit test
- Integration test

### Release note

```release-note
None
```

2021-08-30 08:56 UTC, doitian requested changes

2021-08-30 08:56 UTC, doitian commented on .github/workflows/coverage_report.yaml
> +    # if: |
Please remove changes for debug 😃

2021-09-01 02:29 UTC, chanhsu001 commented
sorry, i'm not familiar with github ci, please change to other one to review, thanks.

2021-09-06 07:14 UTC, doitian approved these changes

2021-09-27 03:48 UTC, quake approved these changes

2021-09-27 03:48 UTC, quake commented
bors r=quake,doitian

2021-09-27 04:38 UTC, merged