Ci workflow v2
nervosnetwork/ckb pull request #3010
Opened 2021-09-06 10:08 UTC by liya2017

### What problem does this PR solve?
Improve CI Workflows. Spilt `ci.yaml` into 17 child workflows. Those workflows triggered by push/pull_request
Support skip jobs run , like `ci-runs-only: [unit_tests, linters]`  just run unit_tests and linters.
Support skip os run, like `ci-runs-on: [windows, ubuntu]` will skip runs on macos 
Bors merge based on ubuntu jobs

### Check List 

Tests

- Unit test
- Integration test

### Release note

```release-note
None
```

2021-09-09 01:37 UTC, doitian requested changes

2021-09-09 01:37 UTC, doitian commented on .github/actions/ci_prologue/action.yml
> +description: 'Greet someone'
Change this to some reasonable description.

2021-09-09 01:37 UTC, doitian commented on .github/actions/ci_prologue/ci_prologue.sh
> + runs_on="$1"
Weird indentation. Please use 2 spaces consistently.

2021-09-09 01:37 UTC, doitian commented on .github/actions/ci_prologue/ci_prologue.sh
> +if [[ $GITHUB_EVENT_NAME == "push" ]];then
Use 2 spaces for indentation.

2021-09-09 01:37 UTC, doitian commented on devtools/ci/requirements.txt
> +#
It seems there are no python scripts now. Could this file be deleted?

2021-09-09 01:37 UTC, doitian commented on devtools/ci/ci_main.sh
> +	ci_linters*)
Use consistent indentation in all shell files.

2021-09-14 01:38 UTC, doitian approved these changes

2021-09-16 04:55 UTC, quake approved these changes

2021-09-16 04:55 UTC, quake commented
bors r=quake,doitian

2021-09-16 04:57 UTC, merged

2021-09-29 02:12 UTC, chanhsu001 commented on devtools/ci/ci_main.sh
> +    argo clippy --version ||  rustup component add clippy
typo issue, please change from "argo" to "cargo",  and "||" hide the error.