fix: blocktemplate test
nervosnetwork/ckb pull request #3068
Opened 2021-09-29 11:29 UTC by zhangsoledad

### What problem does this PR solve?

Problem Summary: 
Since https://github.com/nervosnetwork/ckb/pull/2984, if tx-pool does not sync with chain yet, a blank template will return by request.  this may lead to some block-template tests failed randomly.

### What is changed and how it works?

What's Changed:  Make block-template tests block on status sync.

### Related changes

- PR to update `owner/repo`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test

### Release note 

```release-note
None: Exclude this PR from the release note.
```

2021-09-30 07:14 UTC, quake requested changes

2021-09-30 07:14 UTC, quake commented on chain/src/tests/block_assembler.rs
> +            .get_block_template(None, None, None)
the `bytes_limit` parameter should be same as previous call:

```suggestion
            .get_block_template(Some(300 + *BASIC_BLOCK_SIZE), None, None)
```

2021-10-01 01:04 UTC, quake approved these changes

2021-10-02 06:51 UTC, driftluo approved these changes

2021-10-02 06:51 UTC, driftluo commented
bors r=quake,driftluo

2021-10-02 07:11 UTC, merged