chore: tweak unknown tx hashes limit
nervosnetwork/ckb pull request #3169
Opened 2021-11-07 14:55 UTC by quake

### What problem does this PR solve?

the unknown tx hashes limit should be counted by peer

### Check List 

Tests 

- Unit test
- Integration test

### Release note 

```release-note
Title Only: Include only the PR title in the release note.
```

2021-11-08 06:30 UTC, driftluo approved these changes

2021-11-08 08:36 UTC, keroro520 requested changes

2021-11-08 08:36 UTC, keroro520 commented on sync/src/types/mod.rs
> +        if limit > 0 {
Introducing `unknown_tx_hashes_count` is a strict way to enforce the number of requests to peers. And we have to carefully keep the consistency between `unknown_tx_hashes` and `unknown_tx_hashes_count`.


I suggest an alternative way to mitigate the problem without introducing a new field.

```
-        if unknown_tx_hashes.len() >= MAX_UNKNOWN_TX_HASHES_SIZE {
+        if unknown_tx_hashes.len() >= self.peers().len() * MAX_UNKNOWN_TX_HASHES_SIZE {
+            let mut peer_unknown_counter = HashMap::new();
+            for (_hash, priority) in unknown_tx_hashes.iter() {
+                for peer in priority.peers.iter() {
+                    peer_unknown_counter
+                        .entry(peer)
+                        .and_modify(|e| *e += 1)
+                        .or_insert(1);
+                }
+            }
+            for (peer, count) in peer_unknown_counter {
+                if count > MAX_UNKNOWN_TX_HASHES_SIZE {
+                    // punish this peer
+                }
+            }
+
```

2021-11-15 05:40 UTC, keroro520 commented
https://github.com/nervosnetwork/ckb/pull/3173

2021-11-15 05:40 UTC, closed without merging

2021-11-15 07:24 UTC, quake commented
close via https://github.com/nervosnetwork/ckb/pull/3173