fix: upgrade ckb-vm to fix snapshot behavior
nervosnetwork/ckb pull request #3177
Opened 2021-11-15 09:40 UTC by driftluo

### What problem does this PR solve?

chunk run with the snapshot unable to support the binary replacement behavior of exec, which will cause abnormal behavior after resume.

The upgraded VM supports backing up the current code to the snapshot to fix the above problems.

and https://github.com/nervosnetwork/ckb/pull/3176 should keep its behavior until hardfork Activated

### Check List

Tests

- Unit test
- Integration test

### Release note

```release-note
Title Only: Include only the PR title in the release note.
```

2021-11-15 10:04 UTC, mohanson requested changes

2021-11-15 10:04 UTC, mohanson commented on script/src/syscalls/load_cell_data.rs
> +        // To be consistent with the mainnet, add this flag after hardfork
I made a mistake before. Any write operation to the ckb-vm memory will be marked as dirty, and the correct logic should be:

```rs
machine.memory_mut().init_pages(
            addr,
            memory_size,
            FLAG_EXECUTABLE | FLAG_FREEZED,
            Some(data),
            0,
        )?;
        if !self.dirty_flag_enable {
            let mut current_addr = addr;
            while current_addr < addr + memory_size {
                let page = current_addr / RISCV_PAGESIZE as u64;
                machine.memory_mut().clear_flag(page, FLAG_DIRTY)?;
                current_addr += RISCV_PAGESIZE as u64;
            }
        }
```

2021-11-15 10:13 UTC, quake commented
Suggest to add unit test to cover this PR.

On Mon, Nov 15, 2021, 18:04 Mohanson ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In script/src/syscalls/load_cell_data.rs
> <https://github.com/nervosnetwork/ckb/pull/3177#discussion_r749170422>:
>
> > @@ -104,13 +107,15 @@ impl<'a, DL: CellDataProvider + 'a> LoadCellData<'a, DL> {
>              .load_cell_data(cell)
>              .ok_or(VMError::Unexpected)?
>              .slice((content_offset as usize)..(content_end as usize));
> -        machine.memory_mut().init_pages(
> -            addr,
> -            memory_size,
> -            FLAG_DIRTY | FLAG_EXECUTABLE | FLAG_FREEZED,
> -            Some(data),
> -            0,
> -        )?;
> +        // To be consistent with the mainnet, add this flag after hardfork
>
> I made a mistake before. Any write operation to the ckb-vm memory will be
> marked as dirty, and the correct logic should be:
>
> machine.memory_mut().init_pages(
>             addr,
>             memory_size,
>             FLAG_EXECUTABLE | FLAG_FREEZED,
>             Some(data),
>             0,
>         )?;
>         if !self.dirty_flag_enable {
>             let mut current_addr = addr;
>             while current_addr < addr + memory_size {
>                 let page = current_addr / RISCV_PAGESIZE as u64;
>                 machine.memory_mut().clear_flag(page, FLAG_DIRTY)?;
>                 current_addr += RISCV_PAGESIZE as u64;
>             }
>         }
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/nervosnetwork/ckb/pull/3177#pullrequestreview-805856962>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAACGHTTDGHO4O5A25UWTWLUMDLMVANCNFSM5IBHDRYA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-16 00:49 UTC, yangby-cryptape commented
I pushed #3178 to add more tests, I think that PR should be merged before this PR.

## Notice

#3178 doesn't fix the snapshot behavior.

## How to enable the test for resuming from snapshot?

This PR and my PR has conflicts, so resolved the conflicts at first.
- This PR add `true` for all `LoadCellData::new(..)` in tests, but I think test both `true` and `false` is better.
- Find `is_vm_version_1_and_syscalls_2_enabled` is a bit complicated, I think make a method is better than copied those code twice.

Then find the follow code in `script/src/verify/tests/ckb_latest/features_since_v2021.rs`:

```rust
    // TODO fix resume from snapshot
    let should_be_invalid_permission = script_version <= ScriptVersion::V1;
```

And change the above code as follow:

```diff
-    // TODO fix resume from snapshot
-    let should_be_invalid_permission = script_version <= ScriptVersion::V1;
+    let should_be_invalid_permission = script_version < ScriptVersion::V1;
```

Make sure all tests are passed at last.

2021-11-16 06:39 UTC, yangby-cryptape approved these changes

2021-11-16 06:40 UTC, mohanson approved these changes

2021-11-16 07:18 UTC, zhangsoledad approved these changes

2021-11-16 07:19 UTC, zhangsoledad commented
bors r= yangby-cryptape,mohanson,zhangsoledad

2021-11-16 07:47 UTC, merged