ci(test data): add smoking test report to postgres
nervosnetwork/ckb pull request #3226
Opened 2021-12-10 08:12 UTC by liya2017

### What problem does this PR solve?

Issue Number: close #xxx 

What's Changed:
Add test result to Postgres in order to monitoring it

### Check List 

Tests 

- No code ci-runs-only: [ quick_checks,linters ]

### Release note 

```release-note
Note: Add a note under the PR title in the release note.
```

2021-12-21 03:59 UTC, keroro520 commented on .github/workflows/smoking_test.yaml
> +  PGPASSWORD: ${{ secrets.DB_PASSWORD }}
https://github.com/nervosnetwork/ckb/pull/3224/files#r772809045

2021-12-21 04:08 UTC, keroro520 requested changes

2021-12-21 04:08 UTC, keroro520 commented on .github/workflows/smoking_test.yaml
> +        psql -c "$sql);"
```
psql -c "INSERT INTO smoking_test (
            ...
         )
         VALUES (
            '${{ github.run_id }}',
            '${{ env.state }}',
            '${{ env.start_time }}',
            '$end_time',
            '${{ github.ref_name }}',
            '${{ github.event_name }}',
            'https://github.com/${{ github.repository }}actions/runs/${{ github.run_id }}'
        )"
```

2021-12-21 06:21 UTC, keroro520 approved these changes

2021-12-30 03:49 UTC, doitian approved these changes

2021-12-30 03:50 UTC, doitian commented
bors r=doitian,keroro520

2021-12-30 03:56 UTC, merged