fix: resolve conflict descendants
nervosnetwork/ckb pull request #3264
Opened 2022-01-01 13:28 UTC by zhangsoledad

### What problem does this PR solve?

Previously, pending transaction removed but descendants remain.

### What is changed and how it works?

remove conflict and descendants.

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code ci-runs-only: [ quick_checks,linters ]

### Release note 

```release-note
Title Only: Include only the PR title in the release note.
```

2022-01-04 01:57 UTC, quake requested changes

2022-01-04 01:57 UTC, quake commented on tx-pool/src/process.rs
> +    if mine_mode {
line 1394 and 1395 should be moved to this conditional block:
```
    let mut entries = Vec::new();
    let mut gaps = Vec::new();
```

2022-01-04 01:57 UTC, quake commented on tx-pool/src/process.rs
> +            if let Err(e) = tx_pool.proposed_rtx(cycles, entry.size, entry.rtx.clone()) {
the parameter `cache_entry: Option<CacheEntry>` of `proposed_rtx`  and `gap_rtx` fn may be changed to `cache_entry: CacheEntry`

2022-01-04 01:57 UTC, quake commented on tx-pool/src/process.rs
> +                entries.push((
suggest to change the code:
```
   entries.push(tx_entry.clone();
```

and build the `CachedEntry` in the next loop:
```
for entry in entries {
  tx_pool.proposed_rtx(CacheEntry::completed(tx_entry.cycles, tx_entry.fee), entry.size, entry.rtx.clone())
}
```

2022-01-04 01:57 UTC, quake commented on tx-pool/src/component/pending.rs
> +        use std::collections::VecDeque;
for consistent code style, please move to the header.

2022-01-04 01:57 UTC, quake commented on tx-pool/src/component/pending.rs
> +        let removed = self.inner.remove(id);
```suggestion
        self.inner.remove(id).map(|entry| {
            self.remove_entry_relation(&entry);
            entry
        })
```

2022-01-04 01:57 UTC, quake commented on tx-pool/src/component/pending.rs
> +            }
suggest to use `Entry::Occupied`, which can reduce one hash lookup, this suggestion also apply to `// remove dep` code block

```suggestion
            if let Entry::Occupied(mut entry) = self.inputs.entry(i) {
                let empty = {
                    let ids = entry.get_mut();
                    ids.remove(&tx_short_id);
                    ids.is_empty()
                };
                if empty {
                    entry.remove();
                }
            }
```

2022-01-04 09:08 UTC, quake commented on tx-pool/src/process.rs
> +        // Some(CacheEntry::completed(tx_entry.cycles, tx_entry.fee)),
please remove this line

2022-01-04 09:10 UTC, quake approved these changes

2022-01-06 09:55 UTC, yangby-cryptape approved these changes

2022-01-06 12:18 UTC, quake commented
bors r=quake,yangby-cryptape

2022-01-06 12:24 UTC, merged