Add troubleshoot and metric API for tx-pool
nervosnetwork/ckb pull request #4173
Opened 2023-09-29 00:24 UTC by chenyukang

### What problem does this PR solve?

Problem Summary:

### What is changed and how it works?

- Add troubleshoot API for ckb-cli
- Addd metric API

What's Changed:

### Related changes

- PR to update `owner/repo`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code ci-runs-only: [ quick_checks,linters ]

Side effects

- Performance regression
- Breaking backward compatibility

### Release note 

```release-note
None: Exclude this PR from the release note.

```

2023-09-29 04:13 UTC, eval-exec approved these changes

2023-10-07 02:34 UTC, doitian requested changes

2023-10-07 02:34 UTC, doitian commented on rpc/README.md
> +*   `entry_status`: `string` - The detailed status in tx-pool, `Pending`, `Gap`, `Proposed`
Use pending, gap, proposed to keep the capitalization consistent with other enum types.

2023-10-07 02:35 UTC, doitian commented
Please edit the PR description body.

2023-10-07 09:09 UTC, gpBlockchain commented on rpc/README.md
> +       "score_sortkey": "AncestorsScoreSortKey { fee: Capacity(96942915023), weight: 274, ancestors_fee: Capacity(96942915023), ancestors_weight: 274 }",
remove Capacity  : Capacity(96942915023) -> -0x5b03725df
use hex for `weight` and `ancestors_weight` is better?

2023-11-21 01:47 UTC, doitian approved these changes

2023-11-21 01:47 UTC, doitian commented
Please rebase

2023-11-21 04:12 UTC, merged