Add fuzz on network
nervosnetwork/ckb pull request #4468
Opened 2024-05-23 06:29 UTC by joii2020

Use fuzz to test some code of the network.
Found a bug: 
[AddrManager::fetch_random](https://github.com/nervosnetwork/ckb/blob/develop/network/src/peer_store/addr_manager.rs#L44-L77)

When `count` is 0 and `addr_infos.push(addr_info);`(on line 69) has already been executed, checking `if addr_infos.len() == count` will definitely return false. At this point, it will continue executing all of `self.random_ids` before returning. I believe that in this case, when `count` is 0, it should immediately return an empty `Vec`.

2024-05-23 09:20 UTC, XuJiandong requested changes

2024-05-23 09:20 UTC, XuJiandong commented on network/fuzz/fuzz_targets/fuzz_peer_store.rs
> +    let mut rng = thread_rng();
Don't use rng in fuzzing test. Use random data from input.

2024-05-23 09:20 UTC, XuJiandong commented on network/fuzz/rust-toolchain
> +nightly-2024-05-14
better to choose `nightly`

2024-05-23 09:20 UTC, XuJiandong commented on network/fuzz/src/lib.rs
> +        PeerId::from_bytes(vec![vec![0x12], vec![0x20], d.to_vec()].concat()).unwrap()
0x12, 0x20 can be from random input.

2024-05-23 09:20 UTC, XuJiandong commented on network/fuzz/fuzz_targets/fuzz_peer_store.rs
> +    let now_ms = ckb_systemtime::unix_time_as_millis();
don't use time `now`

2024-05-23 09:20 UTC, XuJiandong commented on network/fuzz/fuzz_targets/fuzz_peer_store.rs
> +    let now_ms = ckb_systemtime::unix_time_as_millis();
Don't use time `now`

2024-05-23 09:20 UTC, XuJiandong commented on network/fuzz/fuzz_targets/fuzz_peer_store.rs
> +    let now_ms = ckb_systemtime::unix_time_as_millis();
Don't use time `now`.

2024-06-11 01:34 UTC, doitian approved these changes

2024-06-11 01:41 UTC, XuJiandong approved these changes

2024-06-13 01:52 UTC, zhangsoledad approved these changes

2024-06-13 02:29 UTC, merged