fix: fix empty git commit version of cli
nervosnetwork/ckb pull request #4629
Opened 2024-08-30 11:44 UTC by xG0Ian

### What problem does this PR solve?

Issue Number: close #4550 nervosnetwork/ckb-cli#609

Problem Summary: When no git information was found, the sub-command --version outputs a pair of empty brackets.

### What is changed and how it works?

What's Changed:
`String::from_utf8(r.stdout)` will always return a string when stdout is empty.
https://github.com/nervosnetwork/ckb/blob/2fb17ab8f4c3a5bd005cbf726e897e3201258bc9/util/build-info/src/lib.rs#L106-L124
https://github.com/nervosnetwork/ckb/blob/2fb17ab8f4c3a5bd005cbf726e897e3201258bc9/util/build-info/src/lib.rs#L129-L141

So `extra_parts.is_empty()` is always return `false`
https://github.com/nervosnetwork/ckb/blob/2fb17ab8f4c3a5bd005cbf726e897e3201258bc9/util/build-info/src/lib.rs#L95

unwrap it with default value "", check if they are empty
```rust
let commit_describe = self.commit_describe.clone().unwrap_or("".to_string());
let commit_date = self.commit_describe.clone().unwrap_or("".to_string());
if !commit_describe.is_empty() || !commit_date.is_empty() {
    write!(f, " ({})", extra_parts.as_slice().join(" "))?;
}
```

### Related changes

- PR to update `owner/repo`:
- Need to cherry-pick to the release branch

### Check List 

Tests 

- Unit test
- Integration test
- Manual test (add detailed scripts or steps below)
- No code ci-runs-only: [ quick_checks,linters ]

Side effects

- Performance regression
- Breaking backward compatibility

### Release note 

```release-note
None: Exclude this PR from the release note.
Title Only: Include only the PR title in the release note.
Note: Add a note under the PR title in the release note.
```

2024-08-30 11:56 UTC, eval-exec commented
Thank you,

The `ckb --version` in the ckb release includes the commit hash, but the ckb-cli does not. I think there might be an issue with the ckb-cli build process, where the git commit hash is not being injected into the ckb-cli binary.

https://github.com/nervosnetwork/ckb/releases/tag/v0.118.0-rc1

![image](https://github.com/user-attachments/assets/35f8c5ef-d8cb-4d18-945c-4b0193ca20ee)

2024-08-30 12:01 UTC, xG0Ian commented
Yes, this PR is only for the problem mentioned in those two open issues.

2024-09-02 08:16 UTC, eval-exec commented
Hello, I'm unsure if there's an issue with the package workflow in ckb-cli, as it doesn't appear to be injecting CKB CLI's Git commit information (https://github.com/nervosnetwork/ckb-cli/blob/develop/.github/workflows/package.yaml).

2024-09-02 08:24 UTC, eval-exec requested changes
`ckb-cli` has been missing its Git commit hash in the output of `ckb-cli --version` since version 1.7.0.

Suggest to submit another PR to [ckb-cli](https://github.com/nervosnetwork/ckb-cli) . @xG0Ian  

![image](https://github.com/user-attachments/assets/0edbe8ab-2dce-4340-8b9f-82e965c22e83)

2024-09-02 08:37 UTC, xG0Ian commented
@eval-exec Hi Eval,

Yes, I’m quite sure the issue is that CKB CLI's Git commit information wasn’t injected, which is why it shows `ckb-cli xxx ( )` with empty parentheses `( )`.

The change in this PR is to fixing where we don’t have Git commit info by ensuring that do not display `( )`. However, we still need to inject the Git commit hash into ckb-cli. I will open an issue to ckb-cli and fix it if I can.

2024-09-02 12:06 UTC, closed without merging